# Generated by Django 5.2.7 on 2025-12-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0002_backupcode_mfaconfiguration_mfalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupcode',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
