# Generated by Django 5.1.4 on 2026-01-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0004_awsaccountconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccountconnection',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MonthlyCostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spend', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_average', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forecast_7d', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('forecast_30d', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myground.awsaccountconnection')),
            ],
        ),
        migrations.CreateModel(
            name='DailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myground.awsaccountconnection')),
            ],
            options={
                'unique_together': {('account', 'date')},
            },
        ),
    ]
