# Generated by Django 5.1.4 on 2026-01-07 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0005_awsaccountconnection_last_synced_monthlycostsummary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsaccountconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
