# Generated by Django 5.1.4 on 2026-01-19 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0006_alter_awsaccountconnection_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentDailySpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('day_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('day_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('day_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('day_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_labels', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dailyspend',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='awsaccountconnection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='monthlycostsummary',
            name='monthly_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='awsaccountconnection',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='dailyspend',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spends', to='myground.awsaccountconnection'),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summary', to='myground.awsaccountconnection'),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='daily_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='forecast_30d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='forecast_7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='total_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='awsaccountconnection',
            unique_together={('user', 'aws_account_id')},
        ),
        migrations.AddIndex(
            model_name='dailyspend',
            index=models.Index(fields=['date'], name='myground_da_date_ce5b4c_idx'),
        ),
        migrations.AddField(
            model_name='recentdailyspend',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recent_spends', to='myground.awsaccountconnection'),
        ),
    ]
