# Generated by Django 5.1.4 on 2026-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0007_recentdailyspend_alter_dailyspend_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='monthly_change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
