# Generated by Django 5.1.4 on 2026-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0008_alter_monthlycostsummary_monthly_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentdailyspend',
            name='day_6',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recentdailyspend',
            name='day_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
