# Generated by Django 5.1.4 on 2026-01-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0009_recentdailyspend_day_6_recentdailyspend_day_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyspend',
            name='amount',
            field=models.DecimalField(decimal_places=9, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='daily_average',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='forecast_30d',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='forecast_7d',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='monthly_change',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlycostsummary',
            name='total_spend',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_1',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_2',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_3',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_4',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_5',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_6',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recentdailyspend',
            name='day_7',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=15),
        ),
    ]
