# Generated by Django 5.1.4 on 2026-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0010_alter_dailyspend_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccountconnection',
            name='last_resource_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
