# Generated by Django 5.1.4 on 2026-02-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0011_awsaccountconnection_last_resource_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_resources', models.IntegerField(default=0)),
                ('ec2_total', models.IntegerField(default=0)),
                ('ec2_running', models.IntegerField(default=0)),
                ('ec2_stopped', models.IntegerField(default=0)),
                ('ec2_avg_running_hours', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('s3_total_buckets', models.IntegerField(default=0)),
                ('s3_avg_age_days', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('lambda_total_functions', models.IntegerField(default=0)),
                ('rds_total_instances', models.IntegerField(default=0)),
                ('load_balancers_total', models.IntegerField(default=0)),
                ('cloudfront_total', models.IntegerField(default=0)),
                ('elasticache_total', models.IntegerField(default=0)),
                ('eks_total', models.IntegerField(default=0)),
                ('api_gateway_total', models.IntegerField(default=0)),
                ('dynamodb_total', models.IntegerField(default=0)),
                ('sqs_total', models.IntegerField(default=0)),
                ('sns_total', models.IntegerField(default=0)),
                ('permissions_issues', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_summary', to='myground.awsaccountconnection')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
