# Generated by Django 5.1.4 on 2026-02-11 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myground', '0012_resourcesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowLevelServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Low level service categories',
            },
        ),
        migrations.CreateModel(
            name='LowLevelServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_gb', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_gb_month', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_gb_second', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('price_per_million', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_million_units', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_10k', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_thousand', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_iops_hour', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_iops_month', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_vcpu_hour', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_dpu_hour', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_connection_minute', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_year', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_device', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_sms', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_image', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('price_per_scan', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('unit', models.CharField(help_text='Description of pricing unit', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='myground.lowlevelservicecategory')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LowLevelServiceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_services', models.IntegerField()),
                ('estimated_monthly_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unique_service_types', models.IntegerField()),
                ('unique_services_discovered', models.IntegerField()),
                ('regions_scanned', models.JSONField(default=list)),
                ('snapshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_duration_seconds', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_level_snapshots', to='myground.awsaccountconnection')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='LowLevelServiceCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resource_count', models.IntegerField()),
                ('region_breakdown', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_level_cost_history', to='myground.awsaccountconnection')),
                ('service_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myground.lowlevelservicedefinition')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('account', 'service_definition', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LowLevelServiceResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=500)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('region', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('estimated_monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_level_resources', to='myground.awsaccountconnection')),
                ('service_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myground.lowlevelservicedefinition')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'region'], name='myground_lo_account_d1f829_idx'), models.Index(fields=['account', 'is_active'], name='myground_lo_account_b483f0_idx')],
                'unique_together': {('account', 'service_definition', 'resource_id', 'region')},
            },
        ),
    ]
